### ISSUE TITLE
imageio.core.fetching.NeedDownloadError

### ISSUE THREAD

**Issue by loveJasmine** [david-gpu/srez#18]
rzai@rzai00:~/prj/srez$ python3 srez_main.py --run train
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/imageio/plugins/ffmpeg.py", line 82, in get_exe
    auto=False)
  File "/usr/local/lib/python3.4/dist-packages/imageio/core/fetching.py", line 102, in get_remote_file
    raise NeedDownloadError()
imageio.core.fetching.NeedDownloadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "srez_main.py", line 1, in <module>
    import srez_demo
  File "/home/rzai/prj/srez/srez_demo.py", line 1, in <module>
    import moviepy.editor as mpe
  File "/usr/local/lib/python3.4/dist-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python3.4/dist-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.4/dist-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python3.4/dist-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()

**Comment by david-gpu** [comment]
According to that log it looks like there's a problem with your moviepy
package. Have you looked into that?

On Dec 19, 2016 9:25 PM, "yk_data" <notifications@github.com> wrote:

rzai@rzai00:~/prj/srez$ python3 srez_main.py --run train
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/imageio/plugins/ffmpeg.py",
line 82, in get_exe
auto=False)
File "/usr/local/lib/python3.4/dist-packages/imageio/core/fetching.py",
line 102, in get_remote_file
raise NeedDownloadError()
imageio.core.fetching.NeedDownloadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "srez_main.py", line 1, in
import srez_demo
File "/home/rzai/prj/srez/srez_demo.py", line 1, in
import moviepy.editor as mpe
File "/usr/local/lib/python3.4/dist-packages/moviepy/editor.py", line 22,
in
from .video.io.VideoFileClip import VideoFileClip
File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/VideoFileClip.py",
line 3, in
from moviepy.video.VideoClip import VideoClip
File "/usr/local/lib/python3.4/dist-packages/moviepy/video/VideoClip.py",
line 20, in
from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
File "/usr/local/lib/python3.4/dist-packages/moviepy/video/io/ffmpeg_writer.py",
line 15, in
from moviepy.config import get_setting
File "/usr/local/lib/python3.4/dist-packages/moviepy/config.py", line 38,
in
FFMPEG_BINARY = get_exe()
File "/usr/local/lib/python3.4/dist-packages/imageio/plugins/ffmpeg.py",
line 86, in get_exe
raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download
it by calling:
imageio.plugins.ffmpeg.download()

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/david-gpu/srez/issues/18>, or mute the thread

**Comment by loveJasmine** [comment]
rzai@rzai00:~/prj/seq2seq-show-att-tell$ sudo pip3 install moviepy
Requirement already satisfied (use --upgrade to upgrade): moviepy in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.4/dist-packages (from moviepy)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python3.4/dist-packages (from moviepy)
Requirement already satisfied (use --upgrade to upgrade): imageio in /usr/local/lib/python3.4/dist-packages (from moviepy)
Requirement already satisfied (use --upgrade to upgrade): tqdm in /usr/local/lib/python3.4/dist-packages (from moviepy)
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/lib/python3/dist-packages (from imageio->moviepy)
Cleaning up...
rzai@rzai00:~/prj/seq2seq-show-att-tell$ 


it looks fine

**Comment by david-gpu** [comment]
Looking at the traceback log you provided it is clear that the error
originates inside moviepy.

**Comment by zoraZHJ** [comment]
I have the same question, have you solved?

**Comment by loveJasmine** [comment]
No

**Comment by zoraZHJ** [comment]
I have solved it just now. @loveJasmine 
fitstly, import imageio
then,   imageio.plugins.ffmpeg.download(),  it will download the ffmpeg

**Comment by david-gpu** [comment]
Thank you, zoraZHJ.

**Comment by loveJasmine** [comment]
it works

**Comment by HowcanoeWang** [comment]
works，thanks very much，suggest put this code into pre-loading part
if new user does not have plugins:
    import imageio
    imageio.plugins.ffmpeg.download()

**Comment by wn13083405221** [comment]
please tell me how to solve the problem in detail,when i typed import imageio, it import: unable to open X server @ error/import.c/ImportImageCommand/358 @zoraZHJ @HowcanoeWang @david-gpu

**Comment by pratik96** [comment]
Can anyone help me where I need to put this code in this code?

#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Use text editor to edit the script and type in valid Instagram username/password

import os
import time
import random
from os import listdir
from os.path import isfile, join
from random import randint
from InstagramAPI import InstagramAPI
import imageio
imageio.plugins.ffmpeg.download()


PhotoPath = "~/igphoto/" # Change Directory to Folder with Pics that you want to upload
IGUSER    = "" # Change to your Instagram USERNAME
PASSWD    = "" # Change to your Instagram Password
# Change to your Photo Hashtag
IGCaption = "#hashtag"

os.chdir(PhotoPath)
ListFiles = [f for f in listdir(PhotoPath) if isfile(join(PhotoPath, f))]
print ("Total Photo in this folder:" + str (len(ListFiles)))

#Start Login and Uploading Photo
igapi = InstagramAPI(IGUSER,PASSWD)
igapi.login() # login

for i in range(len(ListFiles)):
    photo = ListFiles[i]
    print ("Progress :" + str([i+1]) + " of " + str(len(ListFiles)))
    print ("Now Uploading this photo to instagram: " + photo)
    igapi.uploadPhoto(photo,caption=IGCaption,upload_id=None)
    # sleep for random between 600 - 1200s
    n = randint(600,1200)
    print ("Sleep upload for seconds: " + str(n))
    time.sleep(n)

**Comment by arpan8514** [comment]
I got this error particularly in windows platform. In Ubuntu, as I had ffmeg pre-installed so I didn't get the error. Anyway, its resolved.

**Comment by vigneshmohanraj92** [comment]
I have this error NameError: name 'CarDetector' is not defined. Did anyone have this issue before or is there any solution ? Thanks

**Comment by vigneshmohanraj92** [comment]
I have this error NameError: name 'CarDetector' is not defined. Did anyone have this issue before or is there any solution ? Thanks
