### ISSUE TITLE
loss function

### ISSUE THREAD

**Issue by zhou-frank** [david-gpu/srez#27]
hi,I have a puzzle which you used the gene_output's downscale and the features to compute the generator's loss.But I think you should use the gene_output and the labels to compute the generator's loss
.

**Comment by david-gpu** [comment]
The generator's loss has two terms. One term uses the discriminator's output, and that one doesn't use any downscaling. This is the term that causes the generated images to be sharp.

The other term comes from the L1 distance between the downscaled generated image and the downscaled (real) feature. The reason we use a downscaled version is because if we used the full image then the generated images would be blurrier. The goal of the L1 term is to accelerate the convergence of the network, not to produce realistic-looking images.
