### ISSUE TITLE
Long training crashes -- ValueError: GraphDef cannot be larger than 2GB.

### ISSUE THREAD

**Issue by PJK** [david-gpu/srez#35]
Hi, I've noticed that training on about 40k images with `--sample_size=128` crashes after about 3hrs with TensorFlow's `ValueError: GraphDef cannot be larger than 2GB.` error.

This is usually caused by dynamically adding nodes to the TF graph. Any idea what may be causing this?

**Comment by david-gpu** [comment]
Yes, it's a known bug. As you say the problem is related to adding nodes to the TF graph during training. I suggest calling `sess.graph.finalize()` before the training loop so that an exception is raised when the code tries to add a new node.

Sorry I can't be of more help. This was code I wrote a while ago and it's not currently maintained.

**Comment by uranusx86** [comment]
this problem cause by _summarize_progress() which processing output image into image sprite, it will add op to graph.
To solve this problem, you can
1. Use numpy instead tensorflow inside _summarize_progress()
2. Use placeholder inside _summarize_progress(), so it won't add op to graph
