### ISSUE TITLE
Possible with IP camera system?

### ISSUE THREAD

**Issue by chrisvella** [david-gpu/srez#7]
Would this be possible to use with a IP camera system such as ZoneMinder?
Either in real-time or post processing?

**Comment by julien-c** [comment]
What about city-wide CCTV monitoring? Surely there would also be a way to hook into Facebook API to get face recognition and access people's names in real time? What about a deep learning model for criminal threat and nefarious intent?

The business opportunities for this really are endless.

</troll> 😁

**Comment by david-gpu** [comment]
> What about city-wide CCTV monitoring?

A number of people have reached out with thoughts like that.

It's a *terrible* idea.

These reconstructions are necessarily inaccurate. If you use them to comb a large facial database you will get lots of false positives. Think about what that means: innocent people who were not there, who had nothing to do with the crime, will be flagged as suspects and, because the justice system is not perfect, some of them will be convicted. When an innocent person is convicted, you are not only punishing an innocent but also you are letting free the actual person who committed the crime.

This isn't science-fiction. DNA fingerprints have been misused in exactly the same manner; while they are accurate to identify a person out of a small number of suspects, they lead to lots of false positives when misused by searching through a large database. Let's not make the same mistakes again.

Now, going back to the original question.

> Would this be possible to use with a IP camera system such as ZoneMinder?

I don't see why not. But keep in mind that security camera footage will be quite different from the dataset that was used to train this system. Different lighting conditions, different angles, different artifacts like noise or glare, etc. It would not work very well unless you can train it with a large database (e.g. a million faces) produced from actual security cameras.

**Comment by julien-c** [comment]
@david-gpu Of course I was being sarcastic, but Github borked my `</troll>` tag 🤓
