### ISSUE TITLE
After training, how do you pass in a single image to recreate from the data?

### ISSUE THREAD

**Issue by MrRio** [david-gpu/srez#9]

**Comment by david-gpu** [comment]
Sorry, not implemented yet. Currently the demo randomly selects one batch from the dataset and puts it aside before training with the rest of the dataset.

Transforming an arbitrary user-provided image is not supported yet because it will require some preprocessing: aligning (rotating) and cropping the face so that the eyes and mouth are in the right position and then resizing it as necessary.

**Comment by MrRio** [comment]
If it was passed an already cropped, positioning and resized, that should be ok to implement right?

**Comment by MrRio** [comment]
![rio](https://cloud.githubusercontent.com/assets/47539/18224641/908a5c4e-71e5-11e6-81c6-72cee33e9ea9.jpg)

If it supports say passing this in, then someone else could implement the code to generate those.

**Comment by Hotkajun** [comment]
I don't instant what you mean.

**Comment by david-gpu** [comment]
Not currently supported. You will have to manually modify the source code.
